### ISSUE TITLE
Where to document the package itself?

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/dashboard#19]

**Comment by maelle** [comment]
on readthedocs :stuck_out_tongue_winking_eye:

**Comment by mpadge** [comment]
Oooh yeah, good idea! Run `r2readthedocs` into a different branch and serve that via readthedocs!! Thanks!

**Comment by mpadge** [comment]
https://github.com/ropensci-review-tools/ropensci-review-tools/issues/16 now resolved, and this package documented at https://ropensci-review-tools.readthedocs.io/en/latest/dashboard/dashboard.html
