### ISSUE TITLE
Slack integration

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/dashboard#24]
Initially only to get status of editorial team members, to allow vacation status to easily be set there rather than, or as well as, airtable.

**Comment by mpadge** [comment]
That commit adds the function.

## TODO

- [ ] Add envvar here with bot token to access slack API
- [ ] Integrate the result of that function with current editor status functionality to determine current status

**Comment by mpadge** [comment]
@noamross This now includes slack status to identify which editors are flagged as "on leave" in https://ropensci-review-tools.github.io/dashboard/editors.html#general-editors (and stats equivalent). Either airtable or slack can be used to indicate away status. The editors channel description on slack has been updated, as have all links in the channel "Topic." These changes will be documented in a PR to the DevGuide. Can you think of any other ways we should communicate or document this?

**Comment by noamross** [comment]
One issue I'm trying to understand out is how 2- or 3-way sync is supposed to work? There should be a single source of truth for editor status.  Is Slack status synced to the AirTable?

**Comment by mpadge** [comment]
No, slack is not synced to airtable, and so there is no single source of truth. That said, I think that's good here because slack status is (generally) instantaneous; whereas airtable can be used to add additional info like status end dates. I added slack because that's the easiest way for editors to signal unavailable. Happy to iterate if you want ... :question:
