### ISSUE TITLE
Workflow failures

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/dashboard#25]
Issue to ping dev team on workflow failures. Note that [the workflow](https://github.com/ropensci-review-tools/dashboard/blob/main/.github/workflows/publish.yaml) needs an *external* token for the last time which has write privileges here, and full read privileges for the `ropensci` org (to read team memberships). The current token set in this repo is a personal one from me.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed.

**Comment by maelle** [comment]
should we only be notified when the dashboard deploy fails, as opposed to R CMD check?

**Comment by mpadge** [comment]
It does only ping from deploy fails, and that's the first one that has worked, which is good. The problem is [slack](https://github.com/ropensci-review-tools/dashboard/actions/runs/8702414635/job/23866404611#step:8:117) which I don't think can be resolved. Even the [lowest tier](https://github.com/ropensci-review-tools/dashboard/actions/runs/8702414635/job/23866404611#step:8:117) should allow at least 1 query per minute, yet this fails intermittently on one every day or so. I'm just going to ignore it for now, and manually re-run the workflow each time it fails.

**Comment by maelle** [comment]
aaah sorry I had missed that failure, I saw the R CMD check one. Could the issue comment link to the log directly?

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8705894152.

**Comment by mpadge** [comment]
I'm going to close this issue; pings will still be delivered here regardless

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8707293964.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8720665626.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8739196068.

**Comment by maelle** [comment]
Should the comment be posted as a bot? It makes me laugh that you're talking to yourself in these comments @mpadge

**Comment by mpadge** [comment]
Yes, but it would then have to be the review bot. It needs access to ropensci org, to get editor data. But I probably should update to the bot token. We then need to document that somewhere.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8746611971.

**Comment by maelle** [comment]
No it could be GitHub Actions, if you give the workflows write access in this repo.

**Comment by mpadge** [comment]
That's not enough, alas. The key needs admin access to ropensci org for everything to work. But of course i could just use the standard key for this final comment step, and that would resolve me-talking-to-myself anyway. Yeah, good idea me 😜

**Comment by mpadge** [comment]
Re-opening because the standard GH workflow key associated with this repo does not have access to run the cli. It errors with:

> GraphQL: Resource not accessible by integration (addComment)
Error: Process completed with exit code 1.

So still need an explicit key. I'll use the `ropensci-review-bot` key, but also need to clearly document that somewhere.

**Comment by mpadge** [comment]
Reverted to personal token. Tokens need to be from somebody with "owner" roles both here and in ropensci, which even bot doesn't have.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8875921003.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8876238984.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8878318614.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/8994256807.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/9025463316.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/9039705563.

**Comment by maelle** [comment]
```r
Quitting from lines  at lines 373-377 [get-ed-dat-history] (history.qmd)
Error in `httr2::req_perform()`:
! HTTP 429 Too Many Requests.
Backtrace:
 1. dashboard::editor_status(quiet = TRUE, aggregation_period = aggregation_period)
 2. dashboard::editor_vacation_status(airtable_base_id)
 3. dashboard:::get_slack_editors_status()
 4. httr2::req_perform(req)
```

**Comment by mpadge** [comment]
Yeah, that's always the failure, yet it is the worst case of (1) intermittent; and (2) not reproducible. My current approach is just to look at the logs each time a failure is pinged here, and ignore all instances of that error :frowning:

**Comment by maelle** [comment]
not any way to rate limit / retry?

**Comment by mpadge** [comment]
Yeah, i guess that would be a good idea. I'll re-open and catch errors from the slack call. Feel free to PR if you have time. The offending lines are
https://github.com/ropensci-review-tools/dashboard/blob/main/R/editors-slack.R#L32-L33
I guess a `req_retry()` would be the best, and lines to simply return NULL on any errors.

**Comment by mpadge** [comment]
@maelle 429 errors now caught in `req_retry` 3 times, plus additional processing lines for failures. I'll leave this open for a while to make sure no more failures appear, and then (hopefully) close again. Thanks!

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/9393242081.

**Comment by maelle** [comment]
```r
Quitting from lines  at lines 40-49 [get-ed-dat] (editors.qmd)
Error in `data.frame()`:
! arguments imply differing number of rows: 0, 1
Backtrace:
 1. dashboard::editor_status(quiet = TRUE, aggregation_period = aggregation_period)
 6. dashboard (local) `<fn>`(aggregation_period = aggregation_period, quiet = quiet)
 9. base::data.frame(login = editors_stats, stats = TRUE)
```

**Comment by maelle** [comment]
Re-launching a run just to see

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/9393242081.

**Comment by mpadge** [comment]
Thanks @maelle, all fixed with the above commit.

**Comment by maelle** [comment]
wait do we close this issue or not :thinking:

**Comment by mpadge** [comment]
Yeah, sure. It doesn't really matter, but better to have it closed i guess. Thanks

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/9710756343.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/9711534854.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/11310109529.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/11319198320.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/11319198320.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/11324399554.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/11325273686.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/12384223056.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14414520369.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14425192197.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14435216108.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14435216108.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14466538421.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14491666307.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14511713221.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14767497173.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14805850548.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14816240825.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/14827055533.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/16584077318.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/22591120942.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/22591628380.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/24594101918.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/26487469052.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/26487469052.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/26795246310.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/26992040783.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/31287522272.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/32202433727.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/35680201727.

**Comment by mpadge** [comment]
@maelle @mpadge The dashboard workflow has failed at https://github.com/ropensci-review-tools/dashboard/actions/runs/35680201727.
