### ISSUE TITLE
Track review hours reported

### ISSUE THREAD

**Issue by noamross** [ropensci-review-tools/dashboard#37]
It would nice to have a graph of the hours of review time reported.  Something that shows the distribution over time (violin/ridge?)

**Comment by mpadge** [comment]
Done: https://dashboard.ropensci.org/history.html#individual-review-times (There seems to be quarto glitch with `href`s; you may need to scroll/click to get to right place.) Data are plotted as a simple time series of (default) quarterly averages, which I think is sufficient here, and the clearest way to present it. Explanation of data at [top of that section](http://localhost:6146/history.html#review-duration). @noamross Let me know what you think, and/or suggest any changes you like. Thanks!

**Comment by noamross** [comment]
Thanks! For a time series, you are probably right that a simple average
makes sense.  But I'd really like to have a distribution handy.  How about
a separate plot of a histogram of all review times in, say, the past two
years? (Maybe 2 years is the default and the slider can filter it).

**Comment by mpadge** [comment]
Sure, re-opening to address that ...

**Comment by noamross** [comment]
You could do the same for the total review duration

**Comment by noamross** [comment]
e.g., https://ropensci.org/blog/2016/03/28/software-review/#review-takes-a-lot-of-time

**Comment by mpadge** [comment]
Interactive histograms of review durations and times at https://dashboard.ropensci.org/history.html#review-dur-time-histograms. I would have liked a ridgeline-type plot like https://observablehq.com/@observablehq/plot-psr-b1919-21, but (1) we don't really have enough data, and individual years are very chunky; and (2) current state of observable requires data for those kinds of plots to be passed as raw data, so histograms would have to be pre-aggregated, which is messy.

I think this is sufficient for now, but let me know if you want to iterate further. Thanks!

**Comment by noamross** [comment]
Could we use column plots or filled area? These are very visually similar to the time series and columns or filled areas better visually convery the concept.  Also, "Histograms" in the title should be "Distributions", (i.e., the other titles don't say "Line Plots" 😉)
