### ISSUE TITLE
Deliverable: Dashboard components

### ISSUE THREAD

**Issue by mpadge** [ropensci-review-tools/dashboard#7]
- [x] Overall editorial load and review time against historical trend
- [x] Current and recent load, availability, and topic and language capabilities of editors
- [ ] Current editor participation in multiple types of review, including data systems, statistical algorithms Champions Mentorship, and English/Spanish reviews
- [x] By-review status under each editor to allow editors to check in across their portfolio
- [x] Warnings for reviews falling behind schedule and requiring follow-up

**Comment by noamross** [comment]
Agreed on closing for specific issues. 

We should probably at least have a notes field about other responsibilities or context for editors.  It's easy to add a field in https://airtable.com/app8dssb6a7PG6Vwj/pagAG8x0w18MDaZkK / https://airtable.com/app8dssb6a7PG6Vwj/tblIBMYXKsF4DwhEW/viwtCcPZXpi5V8xTX?blocks=hide
